<a href="https://colab.research.google.com/github/nyoons/ESAA/blob/main/2022_10_03_%EA%B3%BC%EC%A0%9C%20%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%20%EC%99%84%EB%B2%BD%EA%B0%80%EC%9D%B4%EB%93%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ch 02. 사이킷런으로 시작하는 머신러닝

>**01.사이킷런 소개와 특징**

사이킷런은 파이썬 머신러닝 라이브러리 중 가장 많이 사용되는 라이브러리. 최근에는 텐서플로, 케라스 등 딥러닝 전문 라이브러리의 강세로 인해 대중적 관심은 감소하지만, 여전히 대표적.
* 파이썬 기반의 다른 머신러닝 패키지로 사이킷런 스타일의 API를 지향할 정도로 쉽고 파이썬스럽다.
* 머신러닝을 위한 다양한 알고리즘과 개발을 위한 편리한 프레임워크와 API 제공
* 오랜 기간 검증, 많은 환경

아나콘다를 설치하면 기본으로 사이킷런까지 설치되지만 제거된다면, pip와 anaconda의 conda (추천, conda install scikit_learn) 명령어 통해 가능.

In [2]:
#pip로 설치
pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
#버전확인
import sklearn
print(sklearn.__version__)

1.0.2


>**02. 첫 번째 머신러닝 만들어 보기 -  붓꽃 품종 예측하기**

붓꽃의 품종을 분류하자. 꽃잎의 길이와 너비, 꽃받침의 길이와 너비 피처를 기반으로 꽃의 품종(setosa=0, vesicolor=1, virginica=2)을 예측
<br/>분류는 대표적인 지도학습 방법. 지도학습은 학습을 위한 다양한 피처와 분류 결정값인 레이블 데이터로 모델을 학습하고, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측. 명확한 정답이 주어진 데이터 세트를 테스트 데잍 세트로 지칭.
<br/>먼저 사이킷런에서 사용한 모듈을 임포트하자. 사이킷런 패키지 내 모듈명은 sklearn으로 시작하는 명명규칙. 

In [5]:
from sklearn.datasets import load_iris #사이킷런에서 자체적으로 제공하는 데이터 세트를 생성하는 모듈의 모임
from sklearn.tree import DecisionTreeClassifier #트리 기반 ML 알고리즘 구현한 클래스 모임
from sklearn.model_selection import train_test_split #학습, 검증, 예측 데이터로 데이터를 분리하거나 최적의 하이퍼 파라미터로 평가하기 위한 모듈 모임

In [6]:
import pandas as pd

#붓꽃 데이터 세트를 로딩
iris=load_iris()

#iris.data는 Iris 데이터 세트에서 피처만으로 된 데이터를 numpy로 가지고 있다.
iris_data=iris.data

#iris.target은 붓꽃 데이터 세트에서 레이블 데이터를 numpy로 가지고 있다.
iris_label=iris.target
print('iris target 값: ', iris_label)
print('iris target 명: ', iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환한다.
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target 값:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명:  ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

다음으로 학습용과 테스트용 데이터를 분리하자. 학습 데이터로 학습된 모델이 얼마나 뛰어난지 평가하려면 테스트 데이터 세트가 필요. 이를 위한 train_test_split(). 이걸 이용하면 학습/테스트 데이터를 test_size 파라미터 입력 값의 비율로 쉽게 분할한다.

In [7]:
#(피처 데이터 세트, 레이블 데이터 세트, 전체 데이터 세트 중 테스트 데이터 세트 비율, 호출할 때마다 같은 학습/테스트용 데이터 세트를 생성하기 위한 난수 발생 값)
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [8]:
#수행해보자

#DecisionTreeClassifier 객체 생성
dt_clf=DecisionTreeClassifier(random_state=11)

#학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [11]:
#학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred=dt_clf.predict(X_test)

예측 결과를 기반으로 의사 결정 트리 기반의 DecisionTreeClassifier 예측 성능을 평가해보자. 정확도를 측정하자. accuracy_score(실제 레이블 데이터 세트, 예측 레이블 데이터 세트) 함수 이용.

In [12]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


여기까지 프로세스 정리하면
* **데이터 세트 분리** : 데이터를 학습/테스트로 분리
* **모델 학습** : 학습 데이터 기반으로 모델 학습
* **예측 수행** : ML 모델을 이용해 테스트 데이터의 분류를 예측
* **평가** : 예측과 실제 비교해 모델 성능 평가

>**03. 사이킷런의 기반 프레임워크 익히기**

1. Estimator 이해 및 fit(), predict() 메서드
<br/>학습을 위한 fit, 예측을 위한 predict. 사이킷런은 매우 많은 유형의 Classifier와 Regressor 클래스를 제공하는데 이 둘을 합쳐 Estimator 클래스 라고 부른다. cross_val_score()같은 evaluation 함수, GridSearchCV와 같은 하이퍼 파라미터 튜닝을 지원하는 클래스 경우 Estimator를 인자로 받는다. 인자로 받은 Estimator에 대해 cross_val_score(), GridSearchCV.fit() 함수 내에서 이 Estimator의 fit()과 predict()를 호출해서 평가하거나 하이퍼 파라미터 튜닝을 수행.
<br/>비지도학습인 차원 축소, 클러스터링, 피처 추출 등을 구현한 클래스 역시 대부분 fit()과 transform()을 적용. fit은 학습이 아니라 입력 데이터의 형태에 맞춰 데이터를 변환, 이후 작업은 transform이 수행. 결합하면 fit_transform(). 사용에 주의.
2. 사이킷런의 주요 모듈
<br/>sklearn.preprocessing : 데이터 전처리에 필요한 가공 기능 제공
<br/>sklearn.feature_selection : 큰 영향을 주는 피처 우선순위로 셀렉션
<br/>skleran.featurn_extraction : 텍스트나 이미지 데이터의 벡터화된 피처 추출
<br/>sklearn.metrics : 분류, 회귀, 클러스터링, 페어와이즈에 대한 다양한 성능 측정 방법 제공
<br/>sklearn.naive_bayes : 가우시안, NB, 다항 분포 NB 등
<br/>sklearn.neighbors : 최근접 이웃 알고리즘 제공
<br/>sklearn.svm : 서포트 벡터 머신 알고리즘 제공
<br/>sklearn.pipeline : 피처 처리 등 변환과 ML 알고리즘 학습, 예측을 묶어서 실행
<br/>등등
3. 내장된 예제 데이터 세트
<br/>분류, 회귀를 연습하기 위한 예제용 / 분류, 클러스터링을 위해 표본 데이터로 생성할 용
<br/>fetch 계열 명령은 크기가 커서 다운받아 홈 디렉터리 아래의 scikit_learn_data라는 서브 디렉토리에 저장한 후 불러들이는 데이터
<br/>분류, 회귀 용도 데이터를 더 보자. 일반적으로 딕셔너리 형태. 키는 보통 data(넘파이 배열 타입), target(분류 시 레이블 값, 회귀 시 결과값, 넘파이 배열 타입), target_name(개별 레이블의 이름, 넘파이 배열 또는 파이썬 리스트 타입), feature_names(피처의 이름, 넘파이 배열 또는 파이썬 리스트 타입), DESCR(데이터 세트, 피처에 대한 설명, 스트링 타입). 

In [14]:
#붓꽃 생성하자, bunch는 파이선 딕셔너리 자료형과 유사
from sklearn.datasets import load_iris

iris_data=load_iris()
print(type(iris_data))

keys=iris_data.keys()
print('붓꽃 데이터 세터의 키들:', keys)

<class 'sklearn.utils.Bunch'>
붓꽃 데이터 세터의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [15]:
#객체의 키가 반환하는 값
print('\n feature_names 의 type: ', type(iris_data.feature_names))
print(' feature_names 의 shape: ', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names 의 type: ', type(iris_data.target_names))
print(' feature_names 의 shape: ', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data 의 type: ', type(iris_data.data))
print(' data 의 shape: ', iris_data.data.shape)
print(iris_data['data'])

print('\n target 의 type: ', type(iris_data.target))
print(' target 의 shape: ', iris_data.target.shape)
print(iris_data.target)


 feature_names 의 type:  <class 'list'>
 feature_names 의 shape:  4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names 의 type:  <class 'numpy.ndarray'>
 feature_names 의 shape:  3
['setosa' 'versicolor' 'virginica']

 data 의 type:  <class 'numpy.ndarray'>
 data 의 shape:  (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2

>**04. Model Selection 모듈 소개**

model_selection 모듈은 학습 데이터와 테스트 데이터 세트를 분리하거나 교차 검증 분할 및 평가, Estimator 하이퍼 파라미터를 튜닝하기 위한 다양한 함수, 클래스 제공

1. 학습/테스트 데이터 세트 분리 - train_test_split()
<br/>테스트 데이터 안쓰고 학습과 예측을 동일 데이터로 진행하면 정확도가 100이겠지. 따라서 예측을 수행하는 데이터 셋은 학습을 수행한 학습용 데이터와 달라야함. train_test_split(피처 데이터 셋, 레이블 데이터 셋, test_size, train_size, shuffle, random_state 등 선택적 파라미터 입력)을 통해 원본 데이터에서 학습/테스트를 분리.

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf=DecisionTreeClassifier()
iris_data=load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [17]:
#정확도 측정
dt_clf.fit(X_train, y_train)
pred=dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9556


2. 교차 검증
<br/>과적합 취약한 약점. 교차 검증 통해 다양한 학습과 평가 수행. 데이터 편중을 막기 위해 별도의 여러 세트로 구성된 학습 데이터셋과 검증 데이터 셋에서 학습과 평가 수행. 
 * K폴드 교차 검증
 <br/>K개의 데이터 폴드 세트를 만들어 K번 만큼 각 폴드 세트에 반복
 * Stratified K 폴드
 <br/>불균형한 분포 가진 레이블 데이터 집합. 
 * 교차 검증을 보다 간편하게 - cross_val_score()
 <br/>kfold에서 폴드 세트 설정하고, for 루프에서 반복으로 학습 및 테스트 데이터의 인덱스를 추출한 뒤, 반복적으로 학습과 예측을 수행했음. 이걸 한번에 수행하자.
 <br/>cross_val_score(**estimator, X, y=None, scoring=None, cv=None**, n_jobs=1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs')


In [18]:
#K폴드 교차 검증
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold=KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기: ', features.shape[0])

붓꽃 데이터 세트 크기:  150


In [20]:
# split() 호출해 교차 검증 수행 시마다 학습과 검증을 반복해 예측 정확도 측정하자.
n_iter=0

#KFold 객체의 split()을 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  #kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test=features[train_index], features[test_index]
  y_train, y_test=label[train_index], label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred=dt_clf.predict(X_test)
  n_iter+=1
  #반복 시 마다 정확도 측정
  accuracy=np.round(accuracy_score(y_test, pred), 4)
  train_size=X_train.shape[0]
  test_size=X_train.shape[0]
  print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기:{3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도: ', np.mean(cv_accuracy))


#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기:120
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기: 120, 검증 데이터 크기:120
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기: 120, 검증 데이터 크기:120
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, 검증 데이터 크기:120
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기: 120, 검증 데이터 크기:120
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도:  0.9


In [21]:
#stratified K 폴드
import pandas as pd

iris=load_iris()
iris_df=pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [24]:
kfold=KFold(n_splits=3)
n_iter=0
for train_index, test_index in kfold.split(iris_df):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('##교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts(), iris_df['label'].value_counts())

# 이 경우 정확도는 0이 될 수 밖에 없지

##교차 검증: 1
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64 0    50
1    50
2    50
Name: label, dtype: int64
##교차 검증: 2
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64 0    50
1    50
2    50
Name: label, dtype: int64
##교차 검증: 3
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64 0    50
1    50
2    50
Name: label, dtype: int64


In [25]:
#stratifiedKFold가 이 문제를 해결
from sklearn.model_selection import StratifiedKFold

skf=StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('##교차검증:{0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

##교차검증:1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
##교차검증:2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
##교차검증:3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [27]:
#데이터 분리하자
dt_clf=DecisionTreeClassifier(random_state=156)

skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

#StratifiedKFold의 split() 호출 시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
  #split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test=features[train_index], features[test_index]
  y_train, y_test=label[train_index], label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred=dt_clf.predict(X_test)

  #반복 시 마다 정확도 측정
  n_iter+=1
  accuracy=np.round(accuracy_score(y_test, pred), 4)
  train_size=X_train.shape[0]
  test_size=X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기:{3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

  #교차 검증별 정확도 및 평균 정확도 계산
  print('\n## 교차 검증별 정확도: ', np.round(cv_accuracy, 4))
  print('## 평균 검증 정확도: ', np.mean(cv_accuracy))


#1 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기:50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

## 교차 검증별 정확도:  [0.98]
## 평균 검증 정확도:  0.98

#2 교차 검증 정확도 :0.94, 학습 데이터 크기: 100, 검증 데이터 크기:50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

## 교차 검증별 정확도:  [0.98 0.94]
## 평균 검증 정확도:  0.96

#3 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기:50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도:  [0.98 0.94 0.98]
## 평균 검증 정확도:  0.9666666666666667


In [28]:
#cross_val_score() 이용
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

#성능 지표는 정확도, 교차 검증 세트는 3개
scores=cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도: ', np.round(scores, 4))
print('평균 검증 정확도: ', np.round(np.mean(scores), 4))

교차 검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9667


3. GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에
<br/>사이킷런은 GridSearchCV를 이용해 Classifier, Regressor 같은 알고리즘에 사용되는 하이퍼 파라미터를 순차적으로 입력하며 최적의 파라미터를 도출하는 방안 제공.
<br/>GridSearchCV 클래스의 생성자로 들어가는 주요 파라미터는 estimator(classifier, regressor, pipeline), param_grid(key+리스트 값을 가지는 딕셔너리), scoring(예측 성능 측정할 평가 방법), cv(교차 검증을 위해 분할되는 세트의 갯수), refit.
<br/>GridSearchCV 객체의 fit()을 수행하면 최고 성능 하이퍼 파라미터 값과 결과값이 best_params_, best_score_ 속성에 기록된다

In [31]:
#예를 들면 -> 총 6회에 걸쳐 파라미터를 순차적으로 바꿔 실행
grid_parameters={'max_depth': [1,2,3],
                 'min_samples_split': [2,3]
                 }
grid_parameters

{'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]}

In [33]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris=load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)
dtree=DecisionTreeClassifier()

###파라미터를 딕셔너리 형태로 설정
parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [34]:
#주요 칼럼만 발췌해서 GridSearchCV 동작 살펴보자
import pandas as pd

#param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정.
### reift=True가 디폴트. True이면 가장 좋은 파라미터 설정으로 재학습시킴.
grid_dtree=GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습, 평가
grid_dtree.fit(X_train, y_train)

#GridSearchCV 결과를 추출해 DF으로 반환
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

# 결과에서 rank가 1이라는건 순위가 가장 높다는 것

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [35]:
print('GridSearchCV 최적 파라미터: ', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터:  {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [36]:
#refit=True 였으니까
#GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator=grid_dtree.best_estimator_

#GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.9667


>**05. 데이터 전처리**

1. 데이터 인코딩
2. 피처 스케이링과 정규화
3. StandardScaler
4. MinMaxScaler
5. 학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점

>**06. 사이킷런으로 수행하는 타이타닉 생존자 예측**