<a href="https://colab.research.google.com/github/nyoons/ESAA/blob/main/2022_09_16_%EC%84%B8%EC%85%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [64]:
pip install generators

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for generators: filename=generators-2020.4.27-py3-none-any.whl size=42882 sha256=ce8229fee550258fe2164d445d9bdf55b8b971f5711dd089a2e1ed0461ca61b9
  Stored in directory: /root/.cache/pip/wheels/9a/7b/dd/e9a917bf0ec0efb75a88aa51cf3703d8f40f51e77529e58289
  Created wheel for strict-functions: filename=strict_functions-2020.2.4-py3-none-any.whl size=15476 sha256=0e109bccd3f5c120e248ec2373fb44bafb18102d499acf046359467d5c1acd90
  Stored in directory: /root/.cache/pip/wheels/21/7a/3c/10008c3e5a4821310b91420fcb14fa3b957cb5c8ca4d506fff
Successfully built generators strict-functions


In [65]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
null_vector= np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [24]:
print(null_vector.nbytes)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
vector_2= np.zeros(10)
vector_2[4]=1
print(vector_2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
vector_3=np.arange(start=10, stop=50)
print(vector_3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
print(vector_3[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [63]:
#내가한거
b=np.array([1,2,0,0,4,0])
print(b[b!=0])

nz = np.nonzero([1,2,0,0,4,0])
print(nz)

[1 2 4]
(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [21]:
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [22]:
d= np.random.random((3, 3, 3))
print(d)

[[[0.32005949 0.1771738  0.67486584]
  [0.62936401 0.35472104 0.16648985]
  [0.40253758 0.91224816 0.72109122]]

 [[0.30486908 0.89997335 0.60090966]
  [0.5604644  0.24672308 0.08737664]
  [0.06562004 0.88791666 0.62048043]]

 [[0.92332329 0.87440321 0.13777742]
  [0.9844145  0.10682526 0.23788022]
  [0.05160479 0.36916366 0.21908593]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [23]:
e=np.random.random((10,10))
print(e)

[[0.15579186 0.92625994 0.78960588 0.07455798 0.64452806 0.63187198
  0.5327642  0.86586793 0.21362786 0.95661697]
 [0.22749195 0.57971275 0.86405539 0.68320025 0.09613484 0.34731913
  0.13017877 0.50747011 0.66475313 0.31413449]
 [0.58946916 0.1329762  0.38533241 0.20181608 0.14850853 0.61941455
  0.01423415 0.90186995 0.90891649 0.41695967]
 [0.25359868 0.33204523 0.87355242 0.49111708 0.94311856 0.20388391
  0.12845766 0.78706525 0.37860351 0.55853734]
 [0.86403516 0.82327687 0.29542706 0.10810441 0.93393587 0.87132006
  0.10764475 0.6452746  0.09467127 0.45903975]
 [0.15567779 0.18789548 0.64238007 0.83664316 0.38756855 0.3223628
  0.80011883 0.51560717 0.24134908 0.37569754]
 [0.08307252 0.80492221 0.78803836 0.56008469 0.56644103 0.4401644
  0.40035746 0.59492255 0.67537184 0.71946193]
 [0.35743323 0.95580534 0.19652206 0.84259429 0.40356089 0.93257288
  0.54289627 0.37871658 0.70242751 0.51696041]
 [0.34648924 0.69052364 0.4432567  0.97452937 0.23778665 0.19224896
  0.11673793 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [26]:
f=np.random.random(30)
print(f)
print(f.mean())

[0.44678054 0.95654648 0.42682204 0.83748002 0.61587009 0.76365608
 0.22779016 0.41110013 0.5985082  0.68967391 0.06702495 0.72612203
 0.06317359 0.63404593 0.03029439 0.44644959 0.77378193 0.1429118
 0.87082526 0.8363319  0.07958414 0.88349541 0.19844377 0.56613972
 0.78941862 0.54995562 0.08057082 0.34486746 0.29702832 0.75436294]
0.5036351950600464


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [31]:
g=np.ones((3,3))
g[1,1]=0
print(g)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [32]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [33]:
mat=np.diag([1, 2, 3, 4], k=-1)
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [37]:
mat=np.zeros((8, 8), dtype=int)
mat[::2, 1::2] = 1
mat[1::2, ::2] = 1  # ::이 아니라 비어있는거, 시작 끝 건너뜀
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [38]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [41]:
random_mat=np.random.random((5,5))
print(random_mat)
Z = (random_mat-np.mean(random_mat)) / (np.std (random_mat))
print(Z)

[[0.36864275 0.68194465 0.6399508  0.12257906 0.88217273]
 [0.19704916 0.24614496 0.65502879 0.91214829 0.45220448]
 [0.49866624 0.7004845  0.5291629  0.30660061 0.66372611]
 [0.91795254 0.21792306 0.1196927  0.05516926 0.98477229]
 [0.31476201 0.9146978  0.47129293 0.18279946 0.53873592]]
[[-0.48013012  0.63969671  0.4895992  -1.35962916  1.35536674]
 [-1.09345264 -0.91797078  0.54349205  1.46250762 -0.18145761]
 [-0.01539053  0.70596321  0.0936129  -0.70188571  0.57457866]
 [ 1.48325359 -1.01884358 -1.3699458  -1.60057028  1.72208569]
 [-0.67271465  1.47162024 -0.11323024 -1.14438497  0.12782947]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [43]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [46]:
multiply= np.dot(np.ones((5,3)), np.ones((3,2)))
print(multiply)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [47]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1 #3에서 8 사이에 있는걸 음수로 바꾸는 함수
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [50]:
print(sum(range(5),-1)) #0,1,2,3,4를 더하고 -1을 더하면 9가 된다
from numpy import *
print(sum(range(5),-1))

10
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [73]:
Z=np.arange(11)

In [74]:
Z**Z

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [69]:
2 << Z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [68]:
Z <- Z

array([False, False, False, False, False, False, False, False, False,
       False])

In [70]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [71]:
Z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [72]:
Z<Z>Z

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-72-6d2bd9eb1fd1>", line 1, in <module>
    Z<Z>Z
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2040, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/

ValueError: ignored

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [58]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3