<a href="https://colab.research.google.com/github/nyoons/ESAA/blob/main/2022_12_05_%EC%84%B8%EC%85%98_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_%EC%B0%A8%EC%9B%90%EC%B6%95%EC%86%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 데이터 로드
from sklearn.datasets import fetch_openml
mnist=fetch_openml('mnist_784', version=1)

In [2]:
# train, test split
X_train = mnist['data'][:60000]
y_train = mnist['target'][:60000]
X_test = mnist['data'][60000:]
y_test = mnist['target'][60000:]

* 랜덤포레스트에 적용

In [18]:
# 랜덤포레스트에 적용 (n_estimators=10, random_state=42)
from sklearn.ensemble import RandomForestClassifier
rcf=RandomForestClassifier(n_estimators=10, random_state=42)

In [19]:
# 정확도 결과
from sklearn.model_selection import cross_val_score
scores=cross_val_score(rcf, X_train, y_train, scoring='accuracy', cv=3)
scores

array([0.94095, 0.9376 , 0.94055])

# 1. PCA

* PCA로 변환한 데이터 세트에 랜덤 포레스트 적용

In [28]:
# PCA 라이브러리 불러오기
from sklearn.decomposition import PCA

In [29]:
# PCA 적용 95% : n_components=0.95
pca=PCA(n_components=0.95)

In [30]:
# PCA 이후 랜덤포레스트 훈련
pca.fit(X_train, y_train)
data_pca=pca.transform(X_train)
print(data_pca.shape)

(60000, 154)


In [31]:
# 정확도 결과 (X_test도 PCA 적용해야합니다.)
pca.fit(X_test, y_test)
scores=cross_val_score(rcf, data_pca, y_train, scoring='accuracy', cv=3)

In [32]:
scores

array([0.87845, 0.8719 , 0.88235])

In [33]:
import numpy as np
np.mean(scores)

0.8775666666666666

# 2. LDA

- LDA로 변환한 데이터 세트에 랜덤 포레스트 적용

In [34]:
# LDA 라이브러리 불러오기
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [35]:
# LDA 적용 : n_components=5
lda=LinearDiscriminantAnalysis(n_components=5)
lda.fit(X_train, y_train)
data_lda=lda.transform(X_train)
print(data_lda.shape)
     

(60000, 5)


In [ ]:
# LDA 이후 랜덤포레스트 훈련


In [36]:
# 정확도 결과 (X_test도 LDA 적용해야합니다.)
lda.fit(X_test, y_test)
scores=cross_val_score(rcf, data_lda, y_train, scoring='accuracy', cv=3)
scores

array([0.8366 , 0.83275, 0.8384 ])

In [37]:
np.mean(scores)

0.8359166666666668