<a href="https://colab.research.google.com/github/nyoons/ESAA/blob/main/%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#01. 머신러닝의 개념
애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
<br/>
ex. 머신러닝은 데이터를 기반으로 숨겨진 패턴을 스스로 인지해 문제를 해결한다.

>**머신러닝의 분류**
*   지도학습 - 분류, 회귀, 추천 시스템, 시각/음성 감지/인지, 텍스트 분석과 NLP
*   비지도학습 - 클러스터링, 차원 축소, 강화학습
*   강화학습

>**데이터 전쟁**
*   머신러닝의 단점은 데이터에 매우 의존적이라는 것. 좋은 품질의 데이터를 향한 경쟁.

>**파이썬과 R 기반의 머신러닝 비교**
*   R - 통계 전용.
*   파이썬 - 다양한 영역. *"소리 없이 프로그래밍 세계를 점령하고 있는 언어"*

#02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지
*   머신러닝 패키지 - **사이킷런**, 텐서플로, 케라스
*   행렬/선형대수/통계 패키지 - **넘파이**, 사이파이
*   데이터 핸들링 - **판다스**(2차원 데이터)
*   시각화 - **맷플롯립**(약간 투박), 시본(맷플롯립을 어느 정도 알아야함)
*   그 외 서드파티 라이브러리
*   주피터 노트북 - 대표적 아이파이썬 지원 툴. 필기하듯.

>**파이썬 머신러닝을 위한 S/W 설치**
1. 아나콘다 설치 - anaconda prompt는 패키지 설치 시 사용. 관리자 권한으로 실행. 
2. visual studio build tools 설치
*   데이터의 추출/가공/변형, 원하는 차원 배열로의 변환 등은 넘파이와 판다스의 몫.

#03. 넘파이
파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적 패키지. 배열 기반의 연산은 물론, 다양한 데이터 핸들링 기능 제공. 하지만 편의성과 다양한 API 지원 측면에서 판다스에 밀림. 상세하게 알 필요는 없지만 **넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요**. 

>**넘파이 ndarray 개요**
<br/>넘파이의 기반 데이터 타입은 ndarray. array()함수는 입력받은 인자(주로 리스트 객체)를 ndarray로 변환하는 기능을 수행. shape변수는 ndarray의 행과 열 수를 튜플 형태로 가지며 ndarray 배열의 차원까지 알 수 있음.

In [ ]:
import numpy as np
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)
array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)
array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1:1차원, array2:2차원, array3: 2차원


>**ndarray의 데이터 타입**
<br/>숫자, 문자열, 불 모두 가능. 하지만 연산 특성상 한 ndarray 내에 같은 데이터 타입만 가능. 다른 타입 섞여있을 경우 더 큰거로 변환. 타입 변경도 astype()으로 가능. 

In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


>**ndarray를 편리하게 생성하기 - arrange, zeros, ones**
<br/>초기화해야하는 경우.

*   range()와 유사한 arange() 이용
*   zeros()는 튜플 형태의 shape값 입력 시 모든 값을 0으로 채운 ndarray 반환
*   ones()는 튜플 형태의 shape값 입력 시 모든 값을 1로 채운 ndarray 반환. dtype 정해주지 않으면 디폴트로 float64형의 데이터로 채움

In [8]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [10]:
zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


>**ndarray의 차원과 크기를 변경하는 reshape()**
<br/>ndarray를 특정 차원 및 크기로 변환.
<br/>인자로 -1을 적용하면 원래 ndarray와 호환되는 새로운 shape로 변환. (-1,1) 형태로 자주 사용되는데 원본 ndarray가 어떤 형태든 2차원이고 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로의 변환을 보장

In [12]:
.array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
#하지만 지정된 사이즈 아니면 오류
array1.reshape(4,3)

ValueError: ignored

In [14]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [15]:
#마찬가지로 사이즈 변경 불가 시 오류
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: ignored

In [17]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist()) #tolist()이용해 리스트 자료형으로 변환

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)


array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


>**넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)**

>**행렬의 정렬 - sort()와 argsort()**

>**선형대수 연산 - 행렬 내적과 전치 행렬 구하기**