<a href="https://colab.research.google.com/github/nyoons/ESAA/blob/main/2022_09_09_%EA%B3%BC%EC%A0%9C_%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%20%EC%99%84%EB%B2%BD%EA%B0%80%EC%9D%B4%EB%93%9C%20%ED%95%84%EC%82%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#01. 머신러닝의 개념
애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
<br/>
ex. 머신러닝은 데이터를 기반으로 숨겨진 패턴을 스스로 인지해 문제를 해결한다.

>**머신러닝의 분류**
*   지도학습 - 분류, 회귀, 추천 시스템, 시각/음성 감지/인지, 텍스트 분석과 NLP
*   비지도학습 - 클러스터링, 차원 축소, 강화학습
*   강화학습

>**데이터 전쟁**
*   머신러닝의 단점은 데이터에 매우 의존적이라는 것. 좋은 품질의 데이터를 향한 경쟁.

>**파이썬과 R 기반의 머신러닝 비교**
*   R - 통계 전용.
*   파이썬 - 다양한 영역. *"소리 없이 프로그래밍 세계를 점령하고 있는 언어"*

#02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지
*   머신러닝 패키지 - **사이킷런**, 텐서플로, 케라스
*   행렬/선형대수/통계 패키지 - **넘파이**, 사이파이
*   데이터 핸들링 - **판다스**(2차원 데이터)
*   시각화 - **맷플롯립**(약간 투박), 시본(맷플롯립을 어느 정도 알아야함)
*   그 외 서드파티 라이브러리
*   주피터 노트북 - 대표적 아이파이썬 지원 툴. 필기하듯.

>**파이썬 머신러닝을 위한 S/W 설치**
1. 아나콘다 설치 - anaconda prompt는 패키지 설치 시 사용. 관리자 권한으로 실행. 
2. visual studio build tools 설치
*   데이터의 추출/가공/변형, 원하는 차원 배열로의 변환 등은 넘파이와 판다스의 몫.

#03. 넘파이
파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적 패키지. 배열 기반의 연산은 물론, 다양한 데이터 핸들링 기능 제공. 하지만 편의성과 다양한 API 지원 측면에서 판다스에 밀림. 상세하게 알 필요는 없지만 **넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요**. 

>**넘파이 ndarray 개요**
<br/>넘파이의 기반 데이터 타입은 ndarray. array()함수는 입력받은 인자(주로 리스트 객체)를 ndarray로 변환하는 기능을 수행. shape변수는 ndarray의 행과 열 수를 튜플 형태로 가지며 ndarray 배열의 차원까지 알 수 있음.

In [ ]:
import numpy as np
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)
array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)
array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1:1차원, array2:2차원, array3: 2차원


>**ndarray의 데이터 타입**
<br/>숫자, 문자열, 불 모두 가능. 하지만 연산 특성상 한 ndarray 내에 같은 데이터 타입만 가능. 다른 타입 섞여있을 경우 더 큰거로 변환. 타입 변경도 astype()으로 가능. 

In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


>**ndarray를 편리하게 생성하기 - arrange, zeros, ones**
<br/>초기화해야하는 경우.

*   range()와 유사한 arange() 이용
*   zeros()는 튜플 형태의 shape값 입력 시 모든 값을 0으로 채운 ndarray 반환
*   ones()는 튜플 형태의 shape값 입력 시 모든 값을 1로 채운 ndarray 반환. dtype 정해주지 않으면 디폴트로 float64형의 데이터로 채움

In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


>**ndarray의 차원과 크기를 변경하는 reshape()**
<br/>ndarray를 특정 차원 및 크기로 변환.
<br/>인자로 -1을 적용하면 원래 ndarray와 호환되는 새로운 shape로 변환. (-1,1) 형태로 자주 사용되는데 원본 ndarray가 어떤 형태든 2차원이고 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로의 변환을 보장

In [ ]:
.array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#하지만 지정된 사이즈 아니면 오류
array1.reshape(4,3)

ValueError: ignored

In [ ]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
#마찬가지로 사이즈 변경 불가 시 오류
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: ignored

In [ ]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist()) #tolist()이용해 리스트 자료형으로 변환

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)


array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


>**넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)**
>1. 특정한 데이터만 추출(단일 값 추출) : 원하는 위치의 인덱스 값 지정 시 해당 데이터 반환, 수정도 가능,
<br/>row/col 대신 axis 0/axis 1 사용
>2. 슬라이싱 : 연속된 엔덱스상의 ndarray 추출 ex. 1:5, ':'기호 앞 뒤로 인덱스 생략 시 자동으로 맨 처음, 맨 마지막 인덱스로 간주
>3. 팬시 인덱싱 : 일정 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환
>4. 불린 인덱싱 : True에 해당하는 인덱스 위치에 있는 데이터 ndarray 반환, 조건 필터링과 검색을 동시에 수행 가능해서 유용

In [ ]:
#단일 값 추출

#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1, stop=10)
print('array1:', array1)
#index는 0부터 시작, array1[2]는 3번째 인덱스 위치의 데이터값 의미
value=array1[2]
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두번째 값:', array1[-2])

array1[0]=9
array1[8]=0
print('array1:', array1)

array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)
print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=1, col=1) index 가리키는 값:', array2d[1,1])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=1, col=1) index 가리키는 값: 5


In [ ]:
#2차원 슬라이싱

array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [ ]:
#팬시 인덱싱

array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())
array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>', array4.tolist())
array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


In [ ]:
#불린 인덱싱

array1=np.arange(start=1, stop=10)
#[]안에 array1d>5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값 : ', array3)

array1>5

boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

array1d>5 불린 인덱싱 결과 값 :  [6 7 8 9]
불린 인덱스로 필터링 결과: [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]


>**행렬의 정렬 - sort()와 argsort()**
>1. 행렬 정렬
<br/>np.sort()와 같이 넘파이에서 sort()를 호출 - 원 행렬 유지
<br/>ndarray.sort()처럼 행렬 자체에서 sort()를 호출 - 원 행렬 자체를 정렬
>2. 정렬된 행렬의 인덱스를 반환하기
<br/>원본 행렬 정렬 된 후 기존 원본 행렬의 원소에 대한 인덱스가 필요할 때 np.argsort()이용, 활용도가 매우 높다

In [ ]:
#행렬 정렬

org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)
#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_Array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)
#내림차순 정렬
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)
#2차원
array2d=np.array([[8,12],
                  [7,1 ]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_Array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [ ]:
#정렬된 행렬의 인덱스를 반환하기

org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

#활용도가 높다
name_array=np.array(['John','Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78,95,84,98,88])
sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]
성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


>**선형대수 연산 - 행렬 내적과 전치 행렬 구하기**
>1. 행렬 내적(행렬 곱)
<br/>np.dot()이용. 왼쪽 행렬 열 개수와 오른쪽 행렬 행 개수 동일해야 가능.
>2. 전치 행렬
<br/>행과 열 위치 교환한 원소로 구성한 행렬. transpose() 이용.

In [ ]:
#행렬 내적

A=np.array( [[1,2,3],
             [4,5,6]] )
B=np.array( [[7,8],
             [9,10],
             [11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

#전치 행렬
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
A의 전치 행렬:
 [[1 3]
 [2 4]]
